spring:
  main:
    allow-circular-references: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/SpringJDBC"
  # url: jdbc:h2:mem:testdb
    username: "postgres"
    password: "123"
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

