drop table if exists book;
drop table if exists Author;
drop table if exists Genre;
CREATE TABLE Book(ID bigint generated by default as identity, NAME VARCHAR(255),AuthorID BIGINT,GenreID BIGINT);
CREATE TABLE Author(ID bigint generated by default as identity, NAME VARCHAR(255));
CREATE TABLE Genre(ID bigint generated by default as identity, NAME VARCHAR(255));