drop table if exists books cascade;
drop table if exists Authors cascade;
drop table if exists Genres cascade;
drop table if exists books_authors cascade;
drop table if exists comments cascade;

create table genres (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id)
);

create table books (
id bigint generated by default as identity,
name varchar(255) not null,
genreid bigint references genres(ID),
primary key (id));

create table authors (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id)
);

create table comments (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id),
bookid bigint references books(ID)
);

create table books_authors(
    book_id bigint references books(id) on delete cascade,
    author_id bigint references authors(id),
    primary key (book_id, author_id)
);



